### PR TITLE
Now using the correct end point to get commit information.

### LINKED ISSUE #94: Broken commit details screen on Android
For some reason at least the Android app is incorrectly requesting commit data to this end point:

`/repos/{org}/{repo}/git/commits/{commit}`

Whereas the [docs](https://developer.github.com/v3/repos/commits/#get-a-single-commit) state this is correct instead (note there's no `git` in the middle):

`/repos/{org}/{repo}/commits/{commit}`

Indeed that's what the mock server is expecting and on master, in the Android app, when you choose a commit from the list you end up in a blank screen.

Gonna send a fix for that now, but more importantly is how ```Scenario: go to commit details``` passes at all. Had a look at the implementation in the steps, which looks very poor as it's only checking that we are in the commit details screen but doesn't check commit details at all.

@martinstolz @emmaguy any reason for that?

### PR DESCRIPTION
**Pull request by juandelgado**
Fixes #94, see docs: https://developer.github.com/v3/repos/commits/#get-a-single-commit

@emmaguy could you please?

### CODE REVIEW

**Comment by juandelgado** [comment]
Ummm, there seems to be something going on. Even with the fix the commit list screen is empty / crashing when trying against the real GitHub API.

**Comment by juandelgado** [comment]
iOS is not even hitting that end point : / I'm guessing it's carrying over the data from the previous screen to screen details.

We should consolidate both.

**Comment by emmaguy** [comment]
I will make android not do another request on the 2nd page, to align with iOS

**Comment by emmaguy** [comment]
WIP on `remove-api-call-commit-details`

**Comment by emmaguy** [comment]
I'll raise a PR

**Pull request closed without merging**
